nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['*']
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTION']
    expose_headers: ['Link']
    max_age: 3600
    hosts: []
    origin_regex: false
    skip_same_as_origin: true
  paths:
    '^/api/':
      allow_origin: ['*']
      allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTION']
      max_age: 3600