nelmio_api_doc:
  documentation:
    info:
      title: NFS API-документация
      description: API-документация
      version: 1.0.0

  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/docs$) # Accepts routes under /api except /api/doc