security:
  enable_authenticator_manager: true

  providers:
    users_in_memory: { memory: null }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

  access_control:
    - { path: ^/, roles: PUBLIC_ACCESS }
