twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
      dateTimeHelper: '@App\Base\Helper\DateTimeHelper'
      contextService: '@App\Service\ContextService\ContextService'
