controllers:
  resource: ../../src/Controller/
  type: attribute

partners_controllers:
  resource: ../../src/Service/PartnerService/Controller/
  type: attribute

kernel:
  resource: ../../src/Kernel.php
  type: attribute
