## Requires the Asset component and the Twig bundle
## $ composer require twig asset
app.swagger_ui:
  path: /api/docs
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
