monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: debug
            handler: nested
            excluded_http_codes: [404, 405]
        nested:
            type: stream
            formatter: 'monolog.formatter.json'
            path: "php://stderr"
            level: error
            channels: ["!event", "!doctrine", "!console"]
#        console:
#            type: console
#            process_psr_3_messages: false
#            channels: ["!event", "!doctrine"]
#            formatter: my_formatter
